name: Hexo

# on: [push, pull_request]
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean
      uses: heowc/action-hexo@1.0.2
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@1.0.2
      with:
        args: generate
    - name: Deploy
      uses: heowc/action-hexo@1.0.2
      env:
        EMAIL: aiyouyou1000@163.com
        NAME: heropoo
      with:
        args: deploy
