name: Hexo

# on: [push, pull_request]
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Node and Hexo
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install hexo-cli -g
    - run: npm install
    - run: hexo g